export interface DocProjectInfo {
  id: string
  title: string
  subtitle: string
  brandColor: string
  brandLogoText?: string
  brandLogoUrl?: string
  year: string
  badgeText: string
  docPath: string
  auditPath?: string
  figmaUrl?: string
  liveUrl?: string
  sizeText: string
  screensCountText: string
  description: string
  highlights: string[]
}

export const docsRegistry: Record<string, DocProjectInfo> = {
  qolaba: {
    id: "qolaba",
    title: "Qolaba AI App",
    subtitle: "Multimodal Generative AI Studio & Diffusion Canvas",
    brandColor: "#3045C9",
    brandLogoText: "Q",
    year: "2023",
    badgeText: "2023 GenAI",
    docPath: "/docs/Qolaba_AI_App_UX_Documentation.md",
    auditPath: "/docs/audits/QOLABA_AI_2023_DESIGN_SYSTEM_AUDIT.md",
    figmaUrl: "https://www.figma.com/design/TwXTBJhwGg3Pi3YzH1sLsp/Qolaba---AI-App--dark-theme?node-id=7-45267",
    sizeText: "296.5 KB · 3,142 Lines",
    screensCountText: "45 Production Assets",
    description: "Enterprise multimodal generative AI creation studio engineered by Pritam Maji in 2023. Eliminates prompt fatigue and black-box waiting through progressive latent previews, 100% token-symmetric obsidian dark mode, and surgical inpainting masks.",
    highlights: [
      "45 Master Production Assets & Design Tokens",
      "Multimodal Canvas with Real-time Denoising Preview",
      "Surgical Inpainting Brush & Generative Fill",
      "Obsidian Dark Substrate (#0B0C10) with WCAG AAA Contrast",
    ],
  },
  brilliant: {
    id: "brilliant",
    title: "Brilliant.org",
    subtitle: "Interactive STEM Learning & Quantitative Intuition",
    brandColor: "#04A777",
    brandLogoText: "B",
    year: "Oct 2022",
    badgeText: "2022 EdTech",
    docPath: "/docs/Brilliant_org_Interactive_Learning_Platform_UX_Documentation.md",
    auditPath: "/docs/audits/BRILLIANT_ORG_2022_DESIGN_SYSTEM_AUDIT.md",
    figmaUrl: "https://www.figma.com/design/NzeSyhIAKyx7DSOEBrmG6l/Pritam-s-Portfolio-List?node-id=1146-17675",
    liveUrl: "https://brilliant.org/",
    sizeText: "477.8 KB · 4,820 Lines",
    screensCountText: "19 Screen Archetypes",
    description: "Pedagogical master architecture architected by Pritam Maji in Oct 2022. Transforms passive STEM video lectures into interactive guided simulations, daily habit formation loops, and micro-stepping scaffolding.",
    highlights: [
      "19 Master Interactive Screen Archetypes",
      "5 STEM Subject Chromatic Taxonomy",
      "Hexagonal Linear Skill Tree Progression",
      "KaTeX & MathML Equation Narration Standards",
    ],
  },
  monday: {
    id: "monday",
    title: "monday.com",
    subtitle: "Enterprise Work OS & Multi-Suite Management",
    brandColor: "#0073EA",
    brandLogoText: "M",
    year: "2022",
    badgeText: "2022 Work OS",
    docPath: "/docs/monday_com_Work_OS_UX_Documentation.md",
    auditPath: "/docs/audits/MONDAY_COM_2022_DESIGN_SYSTEM_AUDIT.md",
    figmaUrl: "https://www.figma.com/design/NzeSyhIAKyx7DSOEBrmG6l/Pritam-s-Portfolio-List?node-id=1143-87",
    liveUrl: "https://monday.com/",
    sizeText: "446.2 KB · 4,510 Lines",
    screensCountText: "21 Screen Archetypes",
    description: "Work OS enterprise reference architecture from 2022. Deconstructs organizational silos through infinite columnar flexibility, real-time battery status distribution, and multi-perspective view virtualization.",
    highlights: [
      "21 Master Screen Hotspot Audits",
      "Vibe Design System W3C DTCG Token Tree",
      "Battery Widget Progress Distribution Algorithm",
      "ARIA role='grid' Virtualized Board Traversal",
    ],
  },
  copyai: {
    id: "copyai",
    title: "Copy.ai",
    subtitle: "Generative AI Content Platform & Workflow Engine",
    brandColor: "#2563EB",
    brandLogoText: "C",
    year: "2021",
    badgeText: "2021 GenAI",
    docPath: "/docs/Copy_ai_Generative_AI_Platform_UX_Documentation.md",
    auditPath: "/docs/audits/COPY_AI_2021_DESIGN_SYSTEM_AUDIT.md",
    figmaUrl: "https://www.figma.com/design/NzeSyhIAKyx7DSOEBrmG6l/Pritam-s-Portfolio-List?node-id=1-52010",
    liveUrl: "https://www.copy.ai/",
    sizeText: "128.8 KB · 1,420 Lines",
    screensCountText: "Generative AI Platform",
    description: "Generative AI writing platform architecture from 2021. Features intuitive prompt structuring, tone-of-voice calibration, and multi-format content generation.",
    highlights: [
      "Enterprise Marketing Copy Generation Pipelines",
      "Tone-of-Voice Parameter Modifiers",
      "Multi-Channel Export & CMS Synchronization",
      "W3C Design System Foundations",
    ],
  },
  github: {
    id: "github",
    title: "GitHub Web",
    subtitle: "Developer Code Review & PR Collaboration Platform",
    brandColor: "#24292F",
    brandLogoText: "GH",
    year: "2019-2020",
    badgeText: "2019-2020 Dev",
    docPath: "/docs/GitHub_Web_Developer_Platform_UX_Documentation.md",
    auditPath: "/docs/audits/GITHUB_WEB_2019_2020_DESIGN_SYSTEM_AUDIT.md",
    figmaUrl: "https://www.figma.com/design/NzeSyhIAKyx7DSOEBrmG6l/Pritam-s-Portfolio-List?node-id=0-1",
    liveUrl: "https://github.com/",
    sizeText: "180.9 KB · 1,980 Lines",
    screensCountText: "18 Screen Archetypes",
    description: "Developer platform master architecture from 2019-2020. Streamlines code review cognitive load through keyboard-first split diffs, inline suggested changes, and Primer design tokens.",
    highlights: [
      "18 Master Repository & PR Review Screens",
      "Primer Design System Dark/Light Substrates",
      "Split & Unified Diff Accessibility Matrix",
      "Home-Row Keyboard Traversal Shortcuts",
    ],
  },
  officevibe: {
    id: "officevibe",
    title: "Officevibe",
    subtitle: "Employee Experience & Continuous Pulse Platform",
    brandColor: "#FF5C5C",
    brandLogoText: "OV",
    year: "2021",
    badgeText: "2021 HR Tech",
    docPath: "/docs/Officevibe_Employee_Experience_Platform_UX_Documentation.md",
    auditPath: "/docs/audits/OFFICEVIBE_2021_DESIGN_SYSTEM_AUDIT.md",
    figmaUrl: "https://www.figma.com/design/NzeSyhIAKyx7DSOEBrmG6l/Pritam-s-Portfolio-List?node-id=1-57423",
    liveUrl: "https://officevibe.com/",
    sizeText: "190.8 KB · 2,110 Lines",
    screensCountText: "19 Screen Archetypes",
    description: "Employee experience platform architecture from 2021. Replaces stressful annual reviews with safe weekly pulse surveys, 10 engagement metrics, and anonymous manager-employee conversations.",
    highlights: [
      "10 Engagement Metric Radar Dimension Cards",
      "Encrypted Anonymous Feedback Chat Drawer",
      "Collaborative 1-on-1 Meeting Agenda Builder",
      "Color-Blind Accessible Sentiment Visualizers",
    ],
  },
  minimal: {
    id: "minimal",
    title: "Minimals UI",
    subtitle: "Universal Design System & Enterprise Application Ecosystem",
    brandColor: "#00A76F",
    brandLogoText: "Min",
    brandLogoUrl: "/logos/minimal.svg",
    year: "2021 Foundation",
    badgeText: "Full Design System",
    docPath: "/docs/Minimal_UI_Design_System_UX_Documentation.md",
    figmaUrl: "https://www.figma.com/design/fL8YGLfjPlERWUkTH8nw5f/Web-r?node-id=0-1",
    sizeText: "140.8 KB · 1,560 Lines",
    screensCountText: "6+ Dashboards & 200+ Atoms",
    description: "Multi-archetype SaaS administration dashboard system with dual navigation rail, OKLCH token engine, and rigorous front-end contracts created by Pritam in 2021.",
    highlights: [
      "Complete Design System Architecture & Multi-Preset Tokens",
      "1:1 Component Parity Between Figma and React / Next.js",
      "Dual Navigation Rails (Vertical, Horizontal, Compact)",
      "WCAG 2.2 AA Contrast Compliance & Fluid Responsiveness",
    ],
  },
  linear: {
    id: "linear",
    title: "Linear App",
    subtitle: "High-Velocity Product Operations Architecture",
    brandColor: "#5E6AD2",
    brandLogoText: "L",
    brandLogoUrl: "/logos/linear.svg",
    year: "Production Spec",
    badgeText: "Sub-50ms Sync",
    docPath: "/docs/Linear_App_UX_Documentation.md",
    figmaUrl: "https://www.figma.com/design/KbEEvOwGnxSPis5uzH5Fq0/Linear-UI?node-id=2202-2",
    liveUrl: "https://linear.app/",
    sizeText: "17.9 KB Architecture Brief",
    screensCountText: "14 Screen Archetypes",
    description: "The purpose-built product management and issue tracking system engineered for high-velocity software teams with sub-50ms keyboard ergonomics.",
    highlights: [
      "14 Master Screen Archetypes (L01–L14)",
      "Sub-50ms Local SQLite Wasm Sync Engine",
      "Bi-directional Git Branch & PR Automation",
      "Obsidian Dark Mode with 100% WCAG AA Contrast",
    ],
  },
  edgetrade: {
    id: "edgetrade",
    title: "EdgeTrade",
    subtitle: "Algorithmic Trading & High-Frequency Terminal",
    brandColor: "#10B981",
    brandLogoText: "E",
    brandLogoUrl: "/logos/edgetrade.svg",
    year: "Live Terminal",
    badgeText: "Live Terminal",
    docPath: "/docs/EdgeTrade_Algorithmic_Terminal_UX_Documentation.md",
    liveUrl: "https://edgetrade-ux.agarthan.space/",
    sizeText: "17.2 KB Architecture Spec",
    screensCountText: "Live Trading Terminal",
    description: "High-frequency trade execution platform featuring dynamic Level-2 order book depth visualizers, sub-millisecond execution, and automated portfolio risk telemetry.",
    highlights: [
      "Sub-millisecond Order Execution Topology",
      "Dynamic Depth Chart & Level-2 Market Visualizer",
      "Margin, Leverage & Liquidation Risk Controls",
      "Multi-Asset Hedging Architecture & Audits",
    ],
  },
  mixpanel: {
    id: "mixpanel",
    title: "Mixpanel",
    subtitle: "Product Intelligence Platform for the AI Era",
    brandColor: "#7856FF",
    brandLogoText: "M",
    brandLogoUrl: "/logos/mixpanel.svg",
    year: "2021 Architecture",
    badgeText: "13 Screens",
    docPath: "/docs/Mixpanel_Product_Intelligence_UX_Documentation.md",
    figmaUrl: "https://mixpanel.com/home/",
    liveUrl: "https://mixpanel.com/",
    sizeText: "23.6 KB Architecture Spec",
    screensCountText: "13 Screen Archetypes",
    description: "The product intelligence platform for the AI era combining event analytics, session replays, and Spark AI insights into a unified decision engine.",
    highlights: [
      "AI-Powered Conversational Insights (Spark AI)",
      "Integrated Session Replay Tied to Event Funnels",
      "Native Multivariate Experiments & Targeted Feature Flags",
      "Warehouse Native Connectors (Snowflake, BigQuery)",
    ],
  },
  frame: {
    id: "frame",
    title: "Frame.so",
    subtitle: "Connected Team Workspace & Operating System",
    brandColor: "#18181B",
    brandLogoText: "F",
    brandLogoUrl: "/logos/frame.png",
    year: "Production Spec",
    badgeText: "10 Screens",
    docPath: "/docs/Frame_so_Connected_Workspace_UX_Documentation.md",
    liveUrl: "https://www.frame.so/",
    sizeText: "13.6 KB Architecture Spec",
    screensCountText: "10 Screen Archetypes",
    description: "A multiplayer connected OS eliminating SaaS fragmentation by seamlessly linking notes to engineering tasks and infinite whiteboards in a single view.",
    highlights: [
      "10 Workspace Core Archetypes (FR01–FR10)",
      "Global CMD+K Search Modal Engine",
      "Bi-directional Doc-to-Task Sync",
      "Unified Real-time Multiplayer Collaboration",
    ],
  },
  miro: {
    id: "miro",
    title: "Miro",
    subtitle: "Multiplayer Visual Workspace & Infinite Canvas",
    brandColor: "#FFD02F",
    brandLogoText: "M",
    brandLogoUrl: "/logos/miro.png",
    year: "2020 Architecture",
    badgeText: "7 Screens",
    docPath: "/docs/Miro_Visual_Workspace_UX_Documentation.md",
    figmaUrl: "https://www.figma.com/design/WjnNoSSAZWFzAkxupduRlo/Miro-UI-myui?node-id=3312-2",
    sizeText: "13.4 KB Architecture Spec",
    screensCountText: "7 Screen Archetypes",
    description: "Hardware-accelerated WebGL infinite canvas powering remote design sprints, interactive sticky note synthesis, and live cursors.",
    highlights: [
      "7 Infinite Canvas Archetypes (M01–M07)",
      "Horizontal Auto-Layout Visual Nodes",
      "WebSocket 60fps Multiplayer Cursors",
      "Spatial Frames & Z-Index Layer Exports",
    ],
  },
  soar: {
    id: "soar",
    title: "Soar",
    subtitle: "Creative Mobile App for FIN Banking & Crypto",
    brandColor: "#8B5CF6",
    brandLogoText: "S",
    year: "Live Mobile UX",
    badgeText: "Live Mobile UX",
    docPath: "/docs/Soar_FinTech_Banking_Crypto_UX_Documentation.md",
    liveUrl: "https://soar.agarthan.space/",
    sizeText: "17.3 KB Architecture Spec",
    screensCountText: "Live FIN & Crypto Mobile App",
    description: "A creative, fluid mobile banking and crypto application engineered for modern digital finance with multi-currency accounts and instant P2P transfers.",
    highlights: [
      "Creative Interface for Modern FIN Banking & Crypto",
      "Unified Multi-Currency Fiat & Digital Asset Portfolios",
      "Instant P2P Transfers & Frictionless Send/Receive Flows",
      "Real-Time Crypto Telemetry & Interactive Asset Visualizers",
    ],
  },
  "fitness-ux-writing": {
    id: "fitness-ux-writing",
    title: "Fitness App UX Writing",
    subtitle: "Mobile Health UX Writing & Case Study",
    brandColor: "#F97316",
    brandLogoText: "Fit",
    year: "Behance Master Case",
    badgeText: "Behance Case",
    docPath: "/docs/Fitness_App_UX_Writing_Documentation.md",
    liveUrl: "https://www.behance.net/gallery/176002683/Fitness-App-UX-Writing",
    sizeText: "34.7 KB Case Study",
    screensCountText: "Behance UX Case Study",
    description: "Comprehensive behavioral UX writing, tone-of-voice frameworks, habit-loop motivational copy, and onboarding conversion case study published on Behance.",
    highlights: [
      "Habit Loop & Behavioral Microcopy Guidelines",
      "Tone of Voice Matrix across User Emotional States",
      "Onboarding Funnel Copy & Friction Reduction",
      "Push Notification Retention Engine Copy",
    ],
  },
}
